<?php

function healthtronicsv2_share_this_menu()
{
    $items = array();
    $items['js-api'] = array(
        'path' => 'api/sharethis',
        'title callback' => FALSE,
        'title' => 'Share This',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'description' => 'Provides a way to email with ajax from the share this form.',
        'page callback' => 'share'
    );
    
    return $items;
}

function share_old()
{
    drupal_add_http_header('Content-Type', 'application/json');
    //print('add_to_list');
    $a = array('one', 'two', 'two', 'three');
    echo drupal_json_output(array_values(array_unique($a)));
}


function share() {
    // All system mails need to specify the module and template key (mirrored from
    // hook_mail()) that the message they want to send comes from.
    $module = 'healthtronicsv2_share_this';
    $key = 'share_form';
    $language = language_default();
    $send = TRUE;
    $node = node_load($_POST['nid']);
    $port = ($_SERVER['SERVER_PORT'] != 80 ) ? ':'.$_SERVER['SERVER_PORT'] : '';
    $url = 'http://' . $_SERVER['SERVER_NAME'] . $port . '/'.drupal_lookup_path('alias','node/'.$node->nid);
    $subject = $node->title;
    
    $params = array(
                    'message'=>$_POST['message'], 
                    'url'=>$url,
                    'subject'=>$subject,
                    );
    
    flood_register_event('share_form', variable_get('share_threshold_window', 60));
    $result = drupal_mail($module, $key, $_POST['to-email'], $language, $params, $_POST['from-email'], $send);
    if ($result['result'] == TRUE) {
        drupal_add_http_header('Content-Type', 'application/json');
        $a = array('status'=>'success', 'to'=>$_POST['to-email'], 'from'=>$_POST['from-email'], 'nodeid'=>$_POST['nid']);
        echo drupal_json_output( $a );
    }
    else {
        drupal_add_http_header('Content-Type', 'application/json');
        $a = array('status'=>'error');
        echo drupal_json_output( $a );
    }
    
}


function healthtronicsv2_share_this_mail_alter(&$message) {
    $node = node_load(arg(1));
    $url = drupal_lookup_path('alias','node/'.$node->nid);
    if($message['module'] != 'healthtronicsv2_share_this') return;
    
    $options = array(
      'langcode' => $message['language']->language,
    );
    $from = $message['from'];
    $message['subject'] = $message['from'] . ' shared a link on HealthTronics.com';
    $message['body'][] = $message['params']['message'];
    $message['body'][] = $message['params']['url'];
    $message['body'][] = "- - -\nYou received this email because someone using the email " . $message["from"] . " sent you a link on HealthTronics.com. You have not been subscribed to an email list.";
}

