<?php

/*
 * Intercept menu building using menu_tree hook.
 * Drupal does note add classes to <ul>
 * so we need to add them here for each menu.
 * #TODO - Look into better approach to modifying <ul> class attributes.
*/

function healthtronicsv2_menu_tree__main_menu($menu)
{
	return '<ul class="nav nav-pills">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_footer_our_company($menu)
{
	return '<ul class="unstyled footer-ul clearfix">' . $menu['tree'] . '</ul>';
}


function healthtronicsv2_menu_tree__menu_footer_for_patients($menu)
{
	return '<ul class="unstyled footer-ul clearfix">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_footer_for_professionals($menu)
{
	return '<ul class="unstyled footer-ul clearfix">' . $menu['tree'] . '</ul>';
}


function healthtronicsv2_menu_tree__menu_physicians_menu($menu)
{
    //var_dump($menu);
	return '<ul class="nav nav-secondary clearfix">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_subnav_patients_menu($menu)
{
	return '<ul class="nav nav-secondary clearfix">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_subnav_our_company_menu($menu)
{
	return '<ul class="nav nav-secondary clearfix">' . $menu['tree'] . '</ul>';
}

/*
 * This sets the main nav menu links class to active depending on the section
 */
function healthtronicsv2_menu_link(array $variables)
{
    $element = $variables['element'];
    $sectionURI = explode('/', $_SERVER['REQUEST_URI']);
    $section = $sectionURI[1];
    if( $variables["element"]["#theme"] == 'menu_link__main_menu')
    {
        $top_nav =ucwords(str_replace('-', ' ', $sectionURI[1]));
        if($top_nav == $element['#title'])
        {
            $element['#localized_options']['attributes']['class'][] = 'active';
        }
    }else{
        if(isset($sectionURI[2]))
        {
            $top_nav =strtolower(str_replace('-', ' ', $sectionURI[2]));
            if($top_nav == strtolower($element['#title']))
            {
                $element['#localized_options']['attributes']['class'][] = 'active';
            }
        }
    }

    $sub_menu = '';
    if ($element['#below']) {
        $sub_menu = drupal_render($element['#below']);
    }
    $output = l($element['#title'], $element['#href'], $element['#localized_options']);
    return '<li' . drupal_attributes($element['#attributes']) . '>' . $output . $sub_menu . "</li>\n";
}
?>