<?php
// intercept menu building
function healthtronicsv2_menu_tree__main_menu($menu)
{
	return '<ul class="nav nav-pills">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_footer_our_company($menu)
{
	return '<ul class="unstyled footer-ul">' . $menu['tree'] . '</ul>';
}


function healthtronicsv2_menu_tree__menu_footer_for_patients($menu)
{
	return '<ul class="unstyled footer-ul">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_footer_for_professionals($menu)
{
	return '<ul class="unstyled footer-ul">' . $menu['tree'] . '</ul>';
}


function healthtronicsv2_menu_tree__menu_physicians_menu($menu)
{
	return '<ul class="nav nav-secondary clearfix">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_subnav_patients_menu($menu)
{
	return '<ul class="nav nav-secondary clearfix">' . $menu['tree'] . '</ul>';
}
?>