<?php

/*
 * Intercept menu building using menu_tree hook.
 * Drupal does note add classes to <ul>
 * so we need to add them here for each menu.
 * #TODO - Look into better approach to modifying <ul> class attributes.
*/

function healthtronicsv2_menu_tree__main_menu($menu)
{
	return '<ul class="nav nav-pills">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_footer_our_company($menu)
{
	return '<ul class="unstyled footer-ul">' . $menu['tree'] . '</ul>';
}


function healthtronicsv2_menu_tree__menu_footer_for_patients($menu)
{
	return '<ul class="unstyled footer-ul">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_footer_for_professionals($menu)
{
	return '<ul class="unstyled footer-ul">' . $menu['tree'] . '</ul>';
}


function healthtronicsv2_menu_tree__menu_physicians_menu($menu)
{
    //var_dump($menu);
	return '<ul class="nav nav-secondary clearfix">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_subnav_patients_menu($menu)
{
	return '<ul class="nav nav-secondary clearfix">' . $menu['tree'] . '</ul>';
}

function healthtronicsv2_menu_tree__menu_subnav_our_company_menu($menu)
{
	return '<ul class="nav nav-secondary clearfix">' . $menu['tree'] . '</ul>';
}

/*
 * This set the sub nav menu links class to 
 * active 
 * #TODO Fix active links
 */
function healthtronicsv2_menu_link(array $variables)
{
    // var_dump(menu_get_active_trail());
    $element = $variables['element'];
    $sectionURI = explode('/', $_SERVER['REQUEST_URI']);
    $section = $sectionURI[1];
    if( $variables["element"]["#theme"] == 'menu_link__main_menu')
    {
        $href = explode('/', drupal_get_path_alias($element['#href']));
        print($sectionURI[1] . '->' . $sectionURI[2] . '->'.$sectionURI[3] . ' ' . $element['#title'] . '<br />');
    }
    
    if($variables["element"]["#theme"] == 'menu_link__menu_physicians_menu')
    {
        //print 'section: ' . $section . '<br/> uri: ' . strtolower(str_replace(" ", "-", $element['#title'])) . '<br .>';
        if($section === strtolower(str_replace(" ", "-", $element['#title'])))
        {
            //$element['#localized_options']['attributes']['class'][] = 'active';   
        }
    }

    $sub_menu = '';
    if ($element['#below']) {
        $sub_menu = drupal_render($element['#below']);
    }
    $output = l($element['#title'], $element['#href'], $element['#localized_options']);
    return '<li' . drupal_attributes($element['#attributes']) . '>' . $output . $sub_menu . "</li>\n";
}
?>