<?php
function healthtronicsv2_block_view_alter(&$data, $block) {
	
	// Subpage Title Block
    if($block->delta == 3)
    {
        $sectionURI = explode('/', $_SERVER['REQUEST_URI']);
        $section = $sectionURI[1];
        $replacements = array('-', '_');
        $section = strtolower(str_replace($replacements, " ", $section));
        if($section == 'search') $section = t('search results');
        $data['content'] = '<h1>' .  ucwords(strtolower($section)) . '</h1>';	    
    }
    
    // Pull Quote Block for subpages. 
    // This lives under the sub_page & news content types left navigation
    if($block->delta == 4)
    {
	    $node = menu_get_object();
        $quote = $node->field_pull_quote['und'][0]['value'];
	    if($node && $node->nid && $quote !== NULL)
	    {
            $data['content'] = '<p class="quote">&ldquo;' . $node->field_pull_quote['und'][0]['value'] . '&rdquo;</p>';
            $data['content'] .= '<p class="citation">&mdash;' . $node->field_pull_quote_author['und'][0]['value'] . '</p>';
	    }else{
            $data['content'] = '';
	    }
    }
}

// Set up custom display modes to be used by event and news nodes
function healthtronicsv2_core_entity_info_alter(&$entity_info) 
{
    $entity_info['node']['view modes']['list_view'] = array(
      'label' => t('List View'),
      'custom settings' => TRUE,
    );
  
    $entity_info['node']['view modes']['feature_view'] = array(
      'label' => t('Feature View'),
      'custom settings' => TRUE,
    );
    
    $entity_info['node']['view modes']['homepage_molecule'] = array(
      'label' => t('Home Page Molecule'),
      'custom settings' => TRUE,
    );
    
    // 
} 


// Removes the advnaced Search form from the search pages.
function healthtronicsv2_form_search_form_alter(&$form, &$form_state, $form_id) {
    switch ($form_id) { // not $form['#id']
        case 'search_form':
            $form['#access'] = FALSE;
            break;
    }
} 


// Style mini pager
function healthtronicsv2__views_mini_pager(&$vars) {
  //print('custom pager');
  // Calculate various markers within this pager piece:
  // Middle is used to "center" pages around the current page.
  $pager_middle = ceil($quantity / 2);
  // current is the page we are currently paged to
  $pager_current = $pager_page_array[$element] + 1;
  // max is the maximum page number
  $pager_max = $pager_total[$element];
  // End of marker calculations.

  $li_previous = theme('pager_previous', (isset($tags[1]) ? $tags[1] : t('‹‹')), $limit, $element, 1, $parameters);
  if (empty($li_previous)) {
    $li_previous = theme('pager_last', t(''), $limit, $element, $parameters);
  }

  $li_next = theme('pager_next', (isset($tags[3]) ? $tags[3] : t('››')), $limit, $element, 1, $parameters);
  if (empty($li_next)) {
	$li_next = theme('pager_first', t(''), $limit, $element, $parameters);
  }

  if ($pager_total[$element] > 1) {
    $items[] = array(
      'class' => 'pager-previous',
      'data' => $li_previous,
    );

    $items[] = array(
      'class' => 'pager-next',
      'data' => $li_next,
    );
    return theme('item_list', $items, NULL, 'ul', array('class' => 'pager'));
  }
} // end function


function healthtronicsv2_pager(&$variables)
{
    //var_dump($variables);
    //print 'total: ' . $total . ' element: ' . $element;
    //pager_default_initialize($total, 1, $element = 0);
    //$output = theme('pager', array('quantity' => $total));
}
?>