<?php

function healthtronicsv2_search_query_node_access_alter(QueryAlterableInterface $query) {
    // Try and see if we are dealing with a node search
	$search = FALSE;
	$node = FALSE;
	foreach ($query->getTables() as $alias => $table) 
	{
		if ($table['table'] == 'search_index') 
		{
			$search = $alias;
		}
		elseif ($table['table'] == 'node') 
		{
			$node = $alias;
		}
	}
	
	if ($node && $search) 
	{
		$excluded_content_types = array('info_graphic');
		$ct = array_map('check_plain', node_type_get_names());
		
		$query->condition($node . '.type', array($excluded_content_types), 'NOT IN');
	}
}

?>