<?php
/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function healthtronicsv2_contact_form_block_info() {

  $blocks['contact_block_form'] = array(
    'info' => t('Contact Form'),
    );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function healthtronicsv2_contact_form_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
 // print 'delta: '.$delta;
  switch ($delta) {
        case 'contact_block_form':
            // Load contact pages inc as the form definition sits there.
            module_load_include('inc', 'contact', 'contact.pages');
            $contact_form = drupal_get_form('contact_site_form');
            $block['content'] = $contact_form;//drupal_get_form('contact_site_form');
            break;
  }
  return $block;
}

function healthtronicsv2_contact_form_form_alter(&$form, &$form_state, $form_id)
{
    $node = node_load(arg(1));
    
    if( $form_id == 'contact_site_form')
    {   
        //var_dump($form);
        unset($form['name']);
        unset($form['copy']);
        unset($form['subject']);
        //
        $form['mail']['#title_display'] = 'invisible';
        $form['mail']['#default_value'] = t('Email Address');
        
        $form['cid']['#title_display'] = 'invisible';
        
        $form['message']['#title_display'] = 'invisible';
        $form['message']['#resizable'] = FALSE;
        $form['message']['#default_value'] = 'Message (optional)';
        $form['cid']['#weight'] = -3;
        $form['cid']["#default_value"] = 0;
        $form['actions']['submit']['#value'] = 'send';
        
        $form['first_name'] = array(
            '#type' => 'textfield',
            '#size' => 30,
            '#weight' => -2,
            //'#attributes'=array('onblur' => 'if (this.value \=\= "") {this.value \="Type in your zipcode";}'),
            '#title' => 'First Name' ,
            '#title_display' => 'invisible',
            '#default_value' => t('First Name'),
            '#required' => TRUE);
            
        $form['last_name'] = array(
            '#type' => 'textfield',
            '#size' => 30,
            '#weight' => -1,
            '#title' => 'Last Name' ,
            '#title_display' => 'invisible',
            '#default_value' => t('Last Name'),
            '#attributes' => array('class="clearfix"'),
            '#required' => TRUE);

       $form['actions']['submit']['#id'] = 'edit-submit';
       $form["#validate"][]='healthtronicsv2_contact_form_form_validate';
       if(isset($node))
       {
           map_taxonomy_to_select($form, $node->field_site_section['und'][0]['taxonomy_term']->name);
       }
       return $form;
    }
}


function healthtronicsv2_contact_form_form_validate($form, &$form_state) {
  if (!$form_state['values']['first_name'] || $form_state['values']['first_name'] == $form['first_name']['#default_value'] ) 
  {
      form_set_error("first_name", t("You must enter a first name."));
      $form_state['rebuild'] = TRUE;
  }
     
  if (!$form_state['values']['last_name'] || $form_state['values']['last_name'] == $form['last_name']['#default_value'] ) 
  {
      form_set_error("last_name", t("You must enter a last name."));
      $form_state['rebuild'] = TRUE;
  }
}

function map_taxonomy_to_select(&$form, $name)
{
    $map   = get_option_map();
    $count = 1;
    
    foreach($form['cid']['#options'] as $option)
    {
        if($map[$name] == $option)
        {
           $form['cid']["#default_value"] = $count;
           //print('<br />found select at index: ' . $count);
           break;
        }else{
            //print '<br />No match - \'' . $option . '\' != \'' . $map[$name] . '\' at index ' . $count;
        }
        
        ++$count;
    }
}
//Website feedback, Software Request
function get_option_map()
{ 
    return array(
        'Resources'=> 'Website  feedback',
        'Patients'=> 'Software Request',
        'Prostate'=> 'Software Request',
        'Why Healthtronics'=> 'Software Request',
        'Our Company'=> 'Website  feedback',
        'News'=> 'Software Request',
        'Events'=> 'Software Request',
        'Facilities'=> 'Software Request',
        'Equipment Services'=> 'Software Request',
        'Cryotherapy'=> 'Software Request',
        'Careers'=> 'Software Request',
        'Laser Treatments'=> 'Software Request',
        'Lithotripsy'=> 'Software Request',
        'Lab Solutions'=> 'Software Request',
        'IT Solutions'=> 'Software Request',
        'Investors'=> 'Software Request',
        'Cancer'=> 'Software Request',
    );
}


