<?php
/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function healthtronicsv2_contact_form_block_info() {

  $blocks['contact_block_form'] = array(
    'info' => t('Contact Form'),
    );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function healthtronicsv2_contact_form_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
 // print 'delta: '.$delta;
  switch ($delta) {
        case 'contact_block_form':
            // Load contact pages inc where the form definition is.
            module_load_include('inc', 'contact', 'contact.pages');
            $contact_form = drupal_get_form('contact_site_form');
            $block['content'] = $contact_form;
            break;
  }
  return $block;
}

// Site Contact Form altered here.
// Used in a block on all pages.
function healthtronicsv2_contact_form_form_alter(&$form, &$form_state, $form_id)
{
    $node = node_load(arg(1));
    
    if( $form_id == 'contact_site_form')
    {   
        unset($form['name']);
        unset($form['copy']);
        unset($form['subject']);
        //
        $form['mail']['#title_display'] = 'invisible';
        $form['mail']['#default_value'] = t('Email Address');
        
        $form['cid']['#title_display'] = 'invisible';
        
        $form['message']['#title_display'] = 'invisible';
        $form['message']['#resizable'] = FALSE;
        $form['message']['#default_value'] = 'Message (optional)';
        $form['cid']['#weight'] = -3;
        $form['cid']["#default_value"] = 0;
        $form['actions']['submit']['#value'] = 'send';
        
        $form['first_name'] = array(
            '#type' => 'textfield',
            '#size' => 30,
            '#weight' => -2,
            // 'onfocus' => "if (this.value == 'Enter Search') {this.value = '';}"
            '#attributes'=>array(
                'onblur' => 'if (this.value == "") {this.value = "First Name";}',
                'onfocus' => 'if (this.value == "First Name") {this.value = "";}'
                ),
            '#title' => 'First Name' ,
            '#title_display' => 'invisible',
            '#default_value' => t('First Name'),
            '#required' => TRUE);
     
        $form['last_name'] = array(
            '#type' => 'textfield',
            '#size' => 30,
            '#weight' => -1,
            '#attributes'=>array(
                'onblur' => 'if (this.value == "") {this.value = "Last Name";}',
                'onfocus' => 'if (this.value == "Last Name") {this.value = "";}'
                ),
            '#title' => 'Last Name' ,
            '#title_display' => 'invisible',
            '#default_value' => t('Last Name'),
            '#attributes' => array('class="clearfix"'),
            '#required' => TRUE);
            
        $form['mail']['#attributes'] = array(
                'onblur' => 'if (this.value == "") {this.value = "Email Address";}',
                'onfocus' => 'if (this.value == "Email Address") {this.value = "";}'
                );
                
        $form['message']['#attributes'] = array(
                'onblur' => 'if (this.value == "") {this.value = "Message (optional)";}',
                'onfocus' => 'if (this.value == "Message (optional)") {this.value = "";}'
                );
                
        $form['actions']['submit']['#id'] = 'edit-submit';
        $form["#validate"][]='healthtronicsv2_contact_form_form_validate';
        $form['#submit'][] = 'healthtronicsv2_contact_form_form_submit';
        // autoselect the form select option based on the pages site category
        if(isset($node))
        {
            map_taxonomy_to_select($form, $node->field_site_section['und'][0]['taxonomy_term']->name);
        }
        var_dump($form);
        return $form;
    }
}

// Custom contact form validation - since we have added a few fields.
function healthtronicsv2_contact_form_form_validate($form, &$form_state) {
  if (!$form_state['values']['first_name'] || $form_state['values']['first_name'] == $form['first_name']['#default_value'] ) 
  {
      form_set_error("first_name", t("You must enter a first name."));
      $form_state['rebuild'] = TRUE;
  }
     
  if (!$form_state['values']['last_name'] || $form_state['values']['last_name'] == $form['last_name']['#default_value'] ) 
  {
      form_set_error("last_name", t("You must enter a last name."));
      $form_state['rebuild'] = TRUE;
  }
}

function healthtronicsv2_contact_form_form_submit($form, &$form_state)
{
    $form_state['redirect'] = 'our-company/contact/confirm';
}

// loop through options and set the default select index
function map_taxonomy_to_select(&$form, $name)
{
    $map   = get_option_map();
    foreach($form['cid']['#options'] as $key => $option)
    {
        if(isset($map[$name]))
        {
           if($map[$name] == $option)
           {
           
              $form['cid']["#default_value"] = $key;
              return;
           }
        }
    }
    
}

/**
 * Map for auto selecting the dropdown on the contact form
 * The array key here is the taxonomy value, the value is the option string in the contact form
 * Option Stringsd in the contact form can be edted at /admin/structure/contact
 */ 

function get_option_map()
{ 
    return array(
        'Our Company'=> 'Contact Us',
        'Lithotripsy'=> 'Lithotripsy',
        'Why Healthtronics'=> 'Software Request',
        'What We Offer'=> 'Facilities',
        'Cryotherapy'=> 'Cryotherapy',
        'Careers'=> 'Software Request',
        'Laser Treatments'=> 'Laser Treatments',
        'Lab Solutions'=> 'Software Request',
        'IT Solutions'=> 'IT Solutions',
        'Investors'=> 'Investors',
        'Equipment Services' => 'Equipment Services',
    );
}


